services:
  leema_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: https://api.leema.kz
        VITE_WS_URL: wss://api.leema.kz/ws
        VITE_GOOGLE_CLIENT_ID: 236011762515-q48adtqtgd72na7lp861339offh3b9k3.apps.googleusercontent.com
        VITE_ENV: production
    container_name: leema_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      # SSL certificates
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  default:
    name: leema_network
    external: true
